### ISSUE TITLE
关于下载错误的问题

### ISSUE THREAD

**Issue by urain39** [urain39/MwgetPy#1]
断点续传暂时还有些bug，原因不明**可能是暂停的时候读写操作被强制停止造成的**。因为断点续传的bug，自动重新分配线程的方案暂不打算实现，不过**线程重分配思路早在之前就已经设计好了**，已部分证实可行性。

**Comment by 95e2** [comment]
使用多进程代替多线程已修复断点续传问题，但有待验证。

**Comment by urain39** [comment]
好像多线程操作本身就有问题，我在使用单纯的start和join方法的早期版本里使用超过16个线程就容易出现文件损坏的问题。但奇怪的是我把bufSize调至64K甚至是16K时损坏有所减少，而在16K以下的8K，4K损坏问题反而增加了。所以有待考虑是否加入新的功能。

**Comment by urain39** [comment]
问题已解决，新功能正在dev分支测试。normal分支将不会被删除，至少暂时不会。
